
server:
  port: 8081
spring:
  application:
    name: Ompra
  datasource:
    url: jdbc:postgresql://dpg-d36h6m0gjchc73cajkkg-a.oregon-postgres.render.com:5432/ompra_39sq
    username: ompra_39sq_user
    password: ZxgE3890M9VmsTFge4H95GwBWyVCkLnF
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
